db:
  driver: mysql
  dsn: root:root@tcp(127.0.0.1:3306)/authorize?parseTime=true&charset=utf8&loc=Asia%2FShanghai
#  driver: sqlite
#  dsn: data/data.db

api:
  name: authorize-api
  addr: 0.0.0.0:8088
  timeout: 5000
  telemetry:
    enable: true

rpc:
  name: authorize-rpc
  addr: 0.0.0.0:8089
  telemetry:
    enable: true