// Code generated by annotation. DO NOT EDIT.
// version: 0.0.6

package annotation

import(
    "github.com/cro4k/annotation/core"
    "github.com/cro4k/authorize/server/api/controller"

)

const (
	TypeFunc   = 1
	TypeStruct = 2
)

var elements = map[string]*core.Element{
    "github.com/cro4k/authorize/server/api/controller.Login": {
		Type: TypeFunc,
		Name: "Login",
		Ptr: controller.Login,
		Path: "github.com/cro4k/authorize/server/api/controller.Login",
		Comments: []string{"Login", "@req [LoginRequest]", "@rsp [LoginResponse]", "@header Content-type:application/json"},
		Annotations: []*core.AnnotationItem{
            {
				Raw: "req [LoginRequest]",
				Annotation: "req [github.com/cro4k/authorize/server/api/controller.LoginRequest]",
				Relation: []interface{}{new(controller.LoginRequest), },
			},
            {
				Raw: "rsp [LoginResponse]",
				Annotation: "rsp [github.com/cro4k/authorize/server/api/controller.LoginResponse]",
				Relation: []interface{}{new(controller.LoginResponse), },
			},
            {
				Raw: "header Content-type:application/json",
				Annotation: "header Content-type:application/json",
				Relation: []interface{}{},
			},
		},
	},
    "github.com/cro4k/authorize/server/api/controller.Register": {
		Type: TypeFunc,
		Name: "Register",
		Ptr: controller.Register,
		Path: "github.com/cro4k/authorize/server/api/controller.Register",
		Comments: []string{"Register", "@req [RegisterRequest]", "@rsp [RegisterResponse]"},
		Annotations: []*core.AnnotationItem{
            {
				Raw: "req [RegisterRequest]",
				Annotation: "req [github.com/cro4k/authorize/server/api/controller.RegisterRequest]",
				Relation: []interface{}{new(controller.RegisterRequest), },
			},
            {
				Raw: "rsp [RegisterResponse]",
				Annotation: "rsp [github.com/cro4k/authorize/server/api/controller.RegisterResponse]",
				Relation: []interface{}{new(controller.RegisterResponse), },
			},
		},
	},
    "github.com/cro4k/authorize/server/api/controller.Logout": {
		Type: TypeFunc,
		Name: "Logout",
		Ptr: controller.Logout,
		Path: "github.com/cro4k/authorize/server/api/controller.Logout",
		Comments: []string{"Logout", "@header Content-type:application/json", "@header Authorization:TOKEN", "@req [LogoutRequest]", "@rsp [LogoutResponse]"},
		Annotations: []*core.AnnotationItem{
            {
				Raw: "header Content-type:application/json",
				Annotation: "header Content-type:application/json",
				Relation: []interface{}{},
			},
            {
				Raw: "header Authorization:TOKEN",
				Annotation: "header Authorization:TOKEN",
				Relation: []interface{}{},
			},
            {
				Raw: "req [LogoutRequest]",
				Annotation: "req [github.com/cro4k/authorize/server/api/controller.LogoutRequest]",
				Relation: []interface{}{new(controller.LogoutRequest), },
			},
            {
				Raw: "rsp [LogoutResponse]",
				Annotation: "rsp [github.com/cro4k/authorize/server/api/controller.LogoutResponse]",
				Relation: []interface{}{new(controller.LogoutResponse), },
			},
		},
	},
}

func Elements() map[string]*core.Element {
	return elements
}

